[project]
name = "homalos"
version = "0.0.1"
description = "基于Python的期货量化交易系统"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "configparser>=7.2.0",
    "loguru>=0.7.3",
    "pandas>=2.3.2",
    "psutil>=7.1.0",
    "pyyaml>=6.0.2",
    "tzdata>=2025.2",
    "watchfiles>=1.1.0",
]
