# 日志配置
log:
  level: "INFO"                         # 日志级别
  # 包含网关名称的日志格式
  has_gateway_format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level}</level> | 
  <magenta>{extra[gateway_name]}</magenta> | <cyan>{extra[module_name]}</cyan> | 
  <cyan>{function}:{line}</cyan> | <level>{message}</level>\n"
  # 不包含网关名称的日志格式
  no_gateway_format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level}</level> | 
  <cyan>{extra[module_name]}</cyan> | <cyan>{function}:{line}</cyan> | <level>{message}</level>\n"
  console:
    enabled: true                       # 控制台日志是否启用

  # 文件日志配置
  file:
    enabled: true                       # 禁用文件日志记录以提高性能
    name_format: "{time:YYYYMMDD}.log"  # 日志文件名格式
    rotation: "100 MB"                  # 当文件超过 100MB 时进行轮转
    retention: "30 days"                # 保留日志的天数
    compression: "zip"                  # 日志压缩格式

  # 特定模块日志级别
  modules:
    event_bus: "DEBUG"                  # 事件总线模块日志级别
    trading_engine: "DEBUG"             # 交易引擎模块日志级别
    strategy_manager: "DEBUG"           # 策略管理器模块日志级别
    risk_manager: "WARNING"             # 风险管理模块日志级别
    order_manager: "DEBUG"              # 订单管理器模块日志级别
    data_service: "DEBUG"               # 数据服务模块日志级别
    ctp_gateway: "DEBUG"                # CTP 网关模块日志级别