# 日志配置
log:
  level: "INFO"
  has_gateway_format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level}</level> | 
  <magenta>{extra[gateway_name]}</magenta> | <cyan>{extra[module_name]}</cyan> | 
  <cyan>{function}:{line}</cyan> | <level>{message}</level>\n"  # 包含网关名称的日志格式
  no_gateway_format: "<green>{time:YYYY-MM-DD HH:mm:ss.SSS}</green> | <level>{level}</level> | 
  <cyan>{extra[module_name]}</cyan> | <cyan>{function}:{line}</cyan> | <level>{message}</level>\n"  # 不包含网关名称的日志格式
  console:
    enabled: true

  file:
    enabled: true  # 禁用文件日志记录以提高性能
    name_format: "{time:YYYYMMDD}.log"
    rotation: "100 MB"  # 当文件超过 100MB 时进行轮转
    retention: "30 days"  # 保留日志的天数
    compression: "zip"

  # 特定模块日志级别
  modules:
    event_bus: "DEBUG"
    trading_engine: "DEBUG"
    strategy_manager: "DEBUG"
    risk_manager: "WARNING"
    order_manager: "DEBUG"
    data_service: "DEBUG"
    ctp_gateway: "DEBUG"