# Homalos期货量化交易系统配置文件
# 配置文件格式参考：https://yaml.org/spec/1.2/spec.html

# 系统基础配置
base:
  name: "Homalos"                                  # 系统名称
  describe: "Homalos Quantitative Trading System"  # 系统描述信息
  version: "0.0.1"                                 # 系统版本号
  data_path: "data/"                               # 数据存储目录
  timezone: "Asia/Shanghai"                        # 系统时区
  # 测试模式配置
  test_mode: false                                 # 是否启用测试模式
  test_trading_hours: true                         # 测试模式下是否绕过交易时间检查

